services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    environment:
      - DATABASE_URI=mysql+aiomysql://tw:hhhggh@db:3306/tw
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tw
      MYSQL_USER: tw
      MYSQL_PASSWORD: hhhggh
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:

