GET http://localhost:8000/

###


POST http://localhost:8000/api/users
Content-Type: application/json

{
  "username": "Test",
  "email": "test@gmail.com",
  "password": "Qwerty123"
}
###

POST http://localhost:8000/api/users
Content-Type: application/json

{
  "username": "admin",
  "email": "admin@gmail.com",
  "password": "Qwerty123"
}
###

POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "Qwerty123"
}

###
GET http://localhost:8000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoidXNlciIsImV4cCI6MTcyOTUzMDk3NX0.zUXC-jZqSVUC-gwPN49qmIWM9C7IKzqOm2_uZwoApcM
