GET http://localhost:8000/

###


POST http://localhost:8000/api/users
Content-Type: application/json

{
  "username": "Test",
  "email": "test@gmail.com",
  "password": "Qwerty123"
}
###

POST http://localhost:8000/api/users
Content-Type: application/json

{
  "username": "admin",
  "email": "admin@gmail.com",
  "password": "Qwerty123"
}
###

POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "Qwerty123"
}

###
GET http://localhost:8000/api/users/me
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoidXNlciIsImV4cCI6MTcyOTgwOTE1NH0.Th9QkL-PzHsgNlQk92ojMBweNKmggdWcPnwnzZwb53w

###
PATCH http://localhost:8000/api/users/ban/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MzAwMjk2NDl9.EH475Fvpe5wMZCMdQp6U4BnL4TmZW7-lcyXqmb1B55s

###
PATCH http://localhost:8000/api/users/unban/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MzAwMjk2NDl9.EH475Fvpe5wMZCMdQp6U4BnL4TmZW7-lcyXqmb1B55s











### Тестування ігор
POST http://localhost:8000/api/games
Content-Type: application/json

{
  "name": "Chess",
  "image": "http://example.com/chess.png",
  "participant_count": [2]
}
###

GET http://localhost:8000/api/games/3
###


GET http://localhost:8000/api/games/
###

GET http://localhost:8000/api/games?search=3

### Тестування матчів
POST http://localhost:8000/api/matches
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoidXNlciIsImV4cCI6MTcyOTg2MDU1OX0.wt4Z8dKbBL1dIpLI13Eo3cmuuwTpIX0YY81A5x2wwHc
Content-Type: application/json

{
  "datetime": "2024-10-22T15:00:00",
  "connection_key": "12345",
  "connection_description": "Match description",
  "stream_url": "http://example.com/stream",
  "password": "matchpassword",
  "game_id": 1,
  "winner_team_id": null
}
###

GET http://localhost:8000/api/matches
###

GET http://localhost:8000/api/matches?status=open
###

GET http://localhost:8000/api/matches?game_id=1&status=completed

###
DELETE http://localhost:8000/api/matches/1

###
PATCH http://localhost:8000/api/matches/join-team/1
Content-Type: application/json

{
  "match_id": 1,
  "team_id": 1,
  "user_id": 4
}

###
PATCH http://localhost:8000/api/matches/complete/1/2

### Тестування команд
POST http://localhost:8000/api/teams
Content-Type: application/json

{
  "name": "Team A",
  "members": ["test@gmail.com", "admin@gmail.com"],
  "match_id": 1
}
###

DELETE http://localhost:8000/api/teams/1
###

GET http://localhost:8000/api/teams/1
###