"""add user-match relation for match owners

Revision ID: 1ac8bcdf6632
Revises: d6e139c39e0b
Create Date: 2024-10-25 11:57:02.115499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac8bcdf6632'
down_revision: Union[str, None] = 'd6e139c39e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_matches_owner_id', 'matches', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_matches_owner_id', 'matches', type_='foreignkey')
    op.drop_column('matches', 'owner_id')
    # ### end Alembic commands ###
