"""add match team relation

Revision ID: 83838eda7aff
Revises: 58f395722777
Create Date: 2024-10-22 09:41:57.082561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83838eda7aff'
down_revision: Union[str, None] = '58f395722777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('winner_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key("winner_team", 'matches', 'teams', ['winner_team_id'], ['id'])
    op.add_column('teams', sa.Column('match_id', sa.Integer(), nullable=True))
    op.create_foreign_key("match", 'teams', 'matches', ['match_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("match", 'teams', type_='foreignkey')
    op.drop_column('teams', 'match_id')
    op.drop_constraint("winner_team", 'matches', type_='foreignkey')
    op.drop_column('matches', 'winner_team_id')
    # ### end Alembic commands ###
