"""added winner id

Revision ID: 9e6c6e7db7e0
Revises: cfa548068520
Create Date: 2024-10-21 23:05:54.851394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e6c6e7db7e0'
down_revision: Union[str, None] = 'cfa548068520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('winner_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matches', 'teams', ['winner_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'winner_team_id')
    # ### end Alembic commands ###
