"""delete status from match table

Revision ID: d6e139c39e0b
Revises: 83838eda7aff
Create Date: 2024-10-25 11:32:55.171934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd6e139c39e0b'
down_revision: Union[str, None] = '83838eda7aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('status', mysql.ENUM('CREATED', 'ACTIVATED', 'OPEN', 'COMPLETED'), nullable=False))
    # ### end Alembic commands ###
